### ISSUE TITLE
CUDA support on linux

### ISSUE THREAD

**Issue by grinco** [royshil/obs-backgroundremoval#242] opened 2023-04-03 16:50 UTC
I installed the plugin using flatpak: https://github.com/flathub/flathub/pull/4016 and only CPU support was available.

The CPU utilization while using the plugin on a 9th gen i7 CPU is 400% (uses half of all available cores at all time). Ideally, we would like to see hardware offloading. This issue is specifically requesting CUDA support on linux.

The plugin has been tested on the following: NVIDIA-SMI 525.105.17 Driver Version: 525.105.17 CUDA Version: 12.0

**Comment by umireon** [comment] 2023-04-06 14:10
I've started to implement CUDA to this plugin #246.

**Comment by umireon** [comment] 2023-04-08 05:16
I've concluded that GPU support on Flatpak is not feasible.

**Comment by umireon** [comment] 2023-04-12 14:39
I've implemented a testing GPU support on Linux. Can you test this deb file?
This requires TensorRT 8.5, CUDA 11.6, and cuDNN 8.2.4. I think the versions must be matched exactly.

https://github.com/royshil/obs-backgroundremoval/suites/12186836154/artifacts/643601399

**Comment by grinco** [comment] 2023-04-12 17:13
I'm using an rpm based system. Do you happen to have an RPM, too? If suggest using build.opensuse.org - they have a great build system that can produce binaries for various os and architectures. Really great stuff. If you point me to the commit or branch you built from I can build it locally, too.

**Comment by grinco** [comment] 2023-04-12 17:14
Nevermind. I see the pull request reference. Will give it a try.

**Comment by umireon** [comment] 2023-04-12 17:54
I'm not sure it works because I don't have Linux with GPU/

**Comment by lgeekjopt** [comment] 2023-04-12 18:29
So i downloaded your zip. And installed your deb
Installed on Mint 21.1 (Ubuntu 22.04). I use obs from ppa. 

"NVIDIA-SMI 510.108.03   Driver Version: 510.108.03   CUDA Version: 11.6"

error: [obs-backgroundremoval] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1106 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libcudnn.so.8:

**Comment by grinco** [comment] 2023-04-12 19:12
@umireon so after compiling it manually for opensuse tumbleweed, I was able to run it, however, I'm getting a lookup error:
obs: symbol lookup error: /usr//lib64/obs-plugins/libonnxruntime_providers_cuda.so: undefined symbol: Provider_GetHost  

I'll try installing cuda 11.6 and cudnn 8.2.4 in a conda environment and see if it helps.

**Comment by lgeekjopt** [comment] 2023-04-12 19:13
same error here. 
obs: symbol lookup error: /usr//lib/x86_64-linux-gnu/obs-plugins/libonnxruntime_providers_cuda.so: undefined symbol: Provider_GetHost

**Comment by umireon** [comment] 2023-04-12 21:44
@grinco @lgeekjopt Can you attach logs here?

**Comment by umireon** [comment] 2023-04-12 22:23
I've created a fix for Provider_GetHost error on #257.

**Comment by ngoonee** [comment] 2023-04-13 07:13
Any change to the build procedure? Trying to test this out on an Arch system.

**Comment by grinco** [comment] 2023-04-13 08:18
> I've created a fix for Provider_GetHost error on #257.

Same results:
tumbleweed ~ (tf2) $ obs
debug: Found portal inhibitor
debug: Attempted path: share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: share/obs/obs-studio/locale.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale.ini
debug: Attempted path: share/obs/obs-studio/themes/Yami.qss
debug: Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
info: Using EGL/X11
info: CPU Name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
info: CPU Speed: 4098.790MHz
info: Physical Cores: 4, Logical Cores: 8
info: Physical Memory: 31490MB Total, 14813MB Free
info: Kernel Version: Linux 6.2.9-1-default
info: Distribution: "openSUSE Tumbleweed" "20230411"
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
info: Qt Version: 5.15.8 (runtime), 5.15.8 (compiled)
info: Portable mode: false
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
info: OBS 29.0.2 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
	max buffering:   960 milliseconds
	buffering type:  dynamically increasing
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA RTX A2000/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 525.105.17, shading language 3.30 NVIDIA via Cg compiler
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1280x720
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          Rec. 709/Partial
info: NV12 texture support not available
info: P010 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
obs: symbol lookup error: /usr//lib64/obs-plugins/libonnxruntime_providers_cuda.so: undefined symbol: Provider_GetHost

**Comment by grinco** [comment] 2023-04-13 10:28
> @grinco I doubt your source code is not the head of #257. Please clean your source code and keep it up to date or please test on Ubuntu first.

I don't have an ubuntu machine. Let's wait for someone with ubuntu to test it, and if it can't be reproduced - i'll assume the issue is on my side. I did do a gh pr checkout 257 in the source repo but it seems you're right - don't have the changes in the pr. I 'll check it later.

**Comment by grinco** [comment] 2023-04-13 11:15
The code seems  right:
commit be0775e82b845d5ddd57418e5bec0cd9ab778b99 (HEAD -> umireon.link-shared, origin/umireon.link-shared)
Author: Kaito Udagawa <umireon@gmail.com>
Date:   Thu Apr 13 07:13:18 2023 +0900

    Format

diff --git a/cmake/FetchOnnxruntime.cmake b/cmake/FetchOnnxruntime.cmake
index 756dbb4..9f725e6 100644
--- a/cmake/FetchOnnxruntime.cmake
+++ b/cmake/FetchOnnxruntime.cmake
@@ -45,11 +45,9 @@ elseif(OS_LINUX)
   FetchContent_MakeAvailable(Onnxruntime)
   set(Onnxruntime_LINK_LIBS
       "${onnxruntime_SOURCE_DIR}/lib/libonnxruntime_providers_shared.so"
-      "${onnxruntime_SOURCE_DIR}/lib/libonnxruntime.so.${Onnxruntime_VERSION}"
-      )
+      "${onnxruntime_SOURCE_DIR}/lib/libonnxruntime.so.${Onnxruntime_VERSION}")
   set(Onnxruntime_INSTALL_LIBS
-      ${Onnxruntime_LINK_LIBS}
-      "${onnxruntime_SOURCE_DIR}/lib/libonnxruntime_providers_cuda.so"
+      ${Onnxruntime_LINK_LIBS} "${onnxruntime_SOURCE_DIR}/lib/libonnxruntime_providers_cuda.so"
       "${onnxruntime_SOURCE_DIR}/lib/libonnxruntime_providers_tensorrt.so")
   target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE ${Onnxruntime_LINK_LIBS})
   target_include_directories(${CMAKE_PROJECT_NAME} SYSTEM



I'll keep digging once I see someone confirm that it works on ubuntu.

**Comment by umireon** [comment] 2023-04-13 11:33
Do you have LINKER:-no-as-needed in the cmake file? This is essential

**Comment by grinco** [comment] 2023-04-13 17:47
I just realized that cuda 12 libraries are being loaded instead of 11. I'll fix the conda env and give it another try.

**Comment by umireon** [comment] 2023-04-14 02:56
I updated #257 branch. Could you try it again? @grinco

**Comment by umireon** [comment] 2023-04-21 03:15
@GenocideStomper #266 available!

**Comment by GenocideStomper** [comment] 2023-04-21 17:26
The build seems to have completed without issues, and I manually installed the generated package: pacman -U obs-backgroundremoval-0.5.17-1-x86_64.pkg.tar.zst

I see that the "Background Removal" plugin moved from Audio/Video Filters to Effect Filters.
As Inference device I have the additional option "GPU - TensorRT". Selecting it seems to keep the filtering on the CPU. If I restart OBS, then the filtering doesn't work until I switch back to CPU. I see no additional load on my GPU (Nvidia GTX 1080). AFAIK I've installed cuda. Are there any specific packages I need?

Some sidenotes not pertaining this issue:
In general I see a better performance in CPU mode compared to version 0.4.0. However in 0.4.0 I've been using SINet, but now it's hiding too little. Had to switch to MediaPipe and adjust the settings to make it work better.

**Comment by grinco** [comment] 2023-04-21 18:13
That's exactly the behavior I'm experiencing. If you will start it from the console you should see the undefined symbol error.

**Comment by GenocideStomper** [comment] 2023-04-21 18:58
You're right. I get the following error when switching to GPU, which I see you posted too:

`error: [obs-backgroundremoval] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1106 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libcudnn.so.8: cannot open shared object file: No such file or directory`

**Comment by umireon** [comment] 2023-04-21 19:03
I found the root cause of Provider_GetHost problem.

**Comment by grinco** [comment] 2023-04-21 19:11
> You're right. I get the following error when switching to GPU, which I see you posted too:
> 
> `error: [obs-backgroundremoval] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1106 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libcudnn.so.8: cannot open shared object file: No such file or directory`

You need to install cudnn...

**Comment by umireon** [comment] 2023-04-21 19:27
I confirmed that #257 now works on my side. Can you try the latest build? @grinco @GenocideStomper

**Comment by GenocideStomper** [comment] 2023-04-22 03:17
So I just took a deep dive into the dependencies and got stuck on the last step.

I've installed cudnn, and for libcublasLt.so.11, libcublas.so.11, libcudart.so.11.0 and libcufft.so.10 I used the 12/11 versions (temporary as a workaround).
Finally I got stuck on libnvinfer.so.8 and libnvinfer_plugin.so.8, which I think should be provided by tensorrt on the AUR, but I can't get it to build.

I might give this another go in a few days.

**Comment by grinco** [comment] 2023-04-22 11:50
You need to install tensorrt from here: https://developer.nvidia.com/tensorrt

**Comment by grinco** [comment] 2023-04-22 12:01
@umireon any way to add CUDA 12 compatibility?

**Comment by umireon** [comment] 2023-04-22 13:32
We can only support CUDA which ONNX Runtime supports.

https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements

The short answer is "no."

**Comment by GenocideStomper** [comment] 2023-04-22 14:09
Are dependencies like tensorrt, cudnn and CUDA 11 available through flatpak? Perhaps that would help the dependencies issue.

**Comment by umireon** [comment] 2023-04-23 01:47
We have to get it worked without FlatPak first because handling CUDA dependencies on FlatPak is extremely hard

**Comment by Zahrun** [comment] 2023-04-23 12:09
I have it working on ubuntu as described in https://github.com/royshil/obs-backgroundremoval/issues/268

**Comment by umireon** [comment] 2023-04-28 11:41
The main problems were addressed and will be released as v0.5.18

**Closed by umireon** 2023-04-28 11:41 UTC
Labels: enhancement
