### ISSUE TITLE
Blur bug on Windows

### ISSUE THREAD

**Issue by royshil** [royshil/obs-backgroundremoval#403] opened 2023-07-24 06:08 UTC
**Describe the bug**

The filter doesn't work. The logs show exception from OpenCV on StackBlur

**Log and Crash Report**

https://obsproject.com/logs/yya5l37lBfgXkepO

**Desktop (please complete the following information):**

 - OS: Win64
 - Plugin Version: 1.1.2
 - OBS Version:29

**Comment by wassupdev** [comment] 2023-07-24 16:40
**Desktop**

- OS: Windows 10 Pro 22H2, build 19045.3208
- Plugin Version: 1.1.2
- OBS Version: 29.1.3 (portable version)

**More details**

- The filter doesn't work in any scenario, 
- Threshold enabled or disabled 
- Settings set to: _0.00_, _0.50_ and _1.00_
- Resolution of the webcam set to 1440p down to 480p
- Tested in other rooms and spaces

**Comment by royshil** [comment] 2023-07-30 10:19
i actually  think the root problem in the logs is 
```
18:06:04.286: Unable to get model filename models/mediapipe.onnx from plugin.
```
the model file is not found and therefore can't get the background mask, and the rest flows from there

i'm not sure why it would do that except for an improper installation of the plugin

**Comment by wassupdev** [comment] 2023-07-30 14:09
yeah, im sorry for the late answer, i tried to set smooth silhouette to 0 and nothing happened, im reinstalling it to see if it makes a difference

**Comment by royshil** [comment] 2023-07-30 15:40
@wassupdev the plugin is unable to access the model files... that is indicative of an installation problem

did you install OBS in a standard location?
can you see if you have a `%appdata%\obs-studio` folder?

**Comment by wassupdev** [comment] 2023-07-30 15:58
i have one at %appdata%\roaming

**Comment by wassupdev** [comment] 2023-07-30 17:21
my actual log, u can see that the dll is being loaded
https://[obsproject.com/logs/NvFSSqe8gWw3CAQq](https://obsproject.com/logs/NvFSSqe8gWw3CAQq)

**Comment by royshil** [comment] 2023-07-30 17:31
Yep - you can see it in OBS I assume as well
but your other log is showing the `mediapipe.onnx` file can't be loaded for w/e reason.
Did you install this with a .zip? or the .exe?
can you please look through `%appdata%\roaming\obs-studio\plugins`?

**Comment by wassupdev** [comment] 2023-07-30 17:44
i tried both, once at time, and get more results out of the .zip
the .exe is the that im actually using, and in the .exe the option for background-removal doesnt even show up
on the %appdata% path, the folder "plugins" doesnt exist, only the one at C:\program files\obs-studio

**Comment by royshil** [comment] 2023-07-30 17:47
so you're using OBS portable? (e.g. with an .exe)
where did you install the `obs-backgroundremoval.dll` file?
the models should be installed along with it in the `data` folder of all the plugins

**Comment by wassupdev** [comment] 2023-07-30 18:32
no, i tried with portable then i gave it up and proceed to do a fresh install of both your plugin and obs studio (when u said .exe i misunderstood as being the installer for obs studio), your plugin has been installed using the installer as well
![image](https://github.com/royshil/obs-backgroundremoval/assets/86902069/8e43a982-02a3-4145-bace-bf46c612c3f3)

**Comment by royshil** [comment] 2023-07-30 19:14
🤔
It looks like the files are in the right place. 
Can we just verify that the model files are indeed in the models folder?

Also let's try to run the filter again and get a fresh log.

**Comment by umireon** [comment] 2023-08-23 13:43
@royshil I think this is not a bug but an installation issue. Since we have not received any response from the author for a while, we can safely close this issue. Can I close this issue?

**Comment by royshil** [comment] 2023-08-23 17:04
@umireon sure. sounds good

**Closed** 2023-08-23 17:07 UTC
Labels: question
