### ISSUE TITLE
Cannot install plugin on Ubuntu 20.04.6 

### ISSUE THREAD

**Issue by Brendan-Leal** [royshil/obs-backgroundremoval#427] opened 2023-08-23 20:51 UTC
**Describe the bug**
Following plugin installation instruction fails to install the plug in properly on Ubuntu

**To Reproduce**

- Ubuntu 20.04.6 
- Install OBS v29.1.3 via official instructions:
`sudo add-apt-repository ppa:obsproject/obs-studio`
`sudo apt update`
`sudo apt install ffmpeg obs-studio`

- Download release: `obs-backgroundremoval-1.1.4-x86_64-linux-gnu.deb`
- run: `sudo dpkg -i ~/Downloads/obs-backgroundremoval-1.1.4-x86_64-linux-gnu.deb `
- open OBS
- Check filters

**Expected behavior**
Plugin shows up as an option in the filters selection in OBS

**Desktop (please complete the following information):**

 - OS: Ubuntu 20.04.6
 - Browser: N/A
 - Plugin Version: 1.1.4
 - OBS Version: 29.1.3

**Comment by umireon** [comment] 2023-08-24 02:47
Please post here the screenshot that indicates the plugin is missing and the OBS log.

**Comment by Brendan-Leal** [comment] 2023-08-24 20:18
![image](https://github.com/royshil/obs-backgroundremoval/assets/51793911/0a348258-a822-4db6-832e-5fca60dc804a)
[2023-08-24 13-15-09.txt](https://github.com/royshil/obs-backgroundremoval/files/12433048/2023-08-24.13-15-09.txt)

**Comment by umireon** [comment] 2023-08-25 02:51
`libQt6Widgets.so.6` is missing on your system but this must exist after the successfull instalattion of OBS.
Can you reinstall obs-studio and try our plugin again?

**Comment by Brendan-Leal** [comment] 2023-08-29 17:52
I tried reinstalling OBS and the plug in. No luck. 

I found this [thread](https://github.com/obs-ndi/obs-ndi/issues/868) talking about a similar issue. I think my best course of action would be to update ubuntu. I appreciate the help nonetheless.  If you have any other suggestions I'd be happy to try them.

**Comment by umireon** [comment] 2023-08-29 21:15
OBS is going to drop the support of Ubuntu 20.04 and thus updating Ubuntu is the best way to resolve this problem.

**Comment by IgnatBeresnev** [comment] 2023-09-14 02:41
Just had this problem on Ubuntu 22.04 after having installed `obs-studio` without adding any repositories. I think that's where the problem is - whatever version is shipped in the default ubuntu repositories must be old and not compatible.

What helped me: I followed the [ubuntu installation instructions](https://obsproject.com/kb/linux-installation), and first added the `obsproject/obs-studio` repository and then re-install `obs-studio`. I immediately got more dependencies, and this problem is no more.

**Comment by umireon** [comment] 2023-09-22 06:22
@royshil Can we close this issue?

**Comment by royshil** [comment] 2023-09-22 12:53
resolved.

**Closed by royshil** 2023-09-22 12:53 UTC
Labels: question
