### ISSUE TITLE
obs: symbol lookup error: /usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so: undefined symbol: cpuinfo_initialize

### ISSUE THREAD

**Issue by piphoser** [royshil/obs-backgroundremoval#195] opened 2023-03-20 18:38 UTC
OBS 29.0.2 from OBS ppa:obsproject/obs-studio repository crashes when adding the backgroundremoval filter with the above error message:  obs: symbol lookup error: /usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so: undefined symbol: cpuinfo_initialize

Is there a dependency I'm missing?

**Comment by royshil** [comment] 2023-03-21 01:17
yes apparently something is wrong
we're looking into it
thanks for the issue

this is a duplicate of #194

**Comment by royshil** [comment] 2023-03-21 01:56
@piphoser  can you try https://github.com/royshil/obs-backgroundremoval/suites/11693307176/artifacts/608110162 ?

**Comment by royshil** [comment] 2023-03-23 01:24
this seems to be resolved

**Closed by royshil** 2023-03-23 01:24 UTC
Labels: bug
