### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by darkarp** [royshil/obs-backgroundremoval#54] opened 2021-11-14 13:53 UTC
Specs:
CPU: i7-9700K 
GPU: RTX 2080 Super 
OS: Windows 11
Segmentation model: Robust Video Matting
CPU Usage: over 90% (unsure, total usage goes to 100% so there may be some throttling)

I'd like to first ask others if this is an issue as well, but also more about trying to figure out if there's a way to make this a bit more efficient to reduce CPU usage. To even have it be usable while playing and streaming 

I had to put it calculating the mask every 4 frames, reducing the CPU to 42-50%, so that with everything else running I get to around 90%. Not a very high quality output of course.

Selecting the GPU as the inference device still makes the CPU work at over 88-90% just for OBS, perhaps there is a way to offload more of the work in an efficient way?

Perhaps this isn't even something that's supposed to happen in the first place, happy to hear some suggestions. I'm using the `Robust Video Matting` because it's what works best for me. All the other ones flicker too much and aren't as accurate. I'm actually incredibly surprised that `Robust Video Matting` is pretty much perfect in terms of its accuracy.

**Comment by royshil** [comment] 2021-11-19 02:48
i'm not 100% sure how to help with that CPU problem. on my Mac it's @ 45% for 1 frame detection and goes to ~20% for 3 frames for detection.
if you don't have the BG remover plugin at all - how much CPU does OBS use?
sometimes OBS for me just uses a lot of CPU for screen capture

**Comment by darkarp** [comment] 2021-11-20 13:36
Without BG remover, OBS runs at around 20% on the CPU. I tried it on my macbook pro and I've experienced something similar to you, it never really goes above 55% with BG remover. My current setup right now is having my macbook doing the BG remover and sending it over to my computer to stream it. Not very optimal.

**Comment by claell** [comment] 2022-07-01 14:43
Duplicate of #23?

**Comment by royshil** [comment] 2023-03-18 14:33
windows now has DirectML wich reduces the CPU usage by 90% even without a GPU

**Closed by royshil** 2023-03-18 14:33 UTC
