### ISSUE TITLE
Applying this plugin to the source with some configuration just results in blinking

### ISSUE THREAD

**Issue by adityastreams** [royshil/obs-backgroundremoval#219] opened 2023-03-27 11:31 UTC
**Describe the bug**
My camera keeps blinking no matter the settings I change, it just blinks with all of the background

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Plugin Version [e.g. 0.5.1] (Newest) 
- OBS Version [29]

**Comment by umireon** [comment] 2023-03-27 15:19
Duplicate of #212

**Comment by umireon** [comment] 2023-03-29 04:11
https://github.com/royshil/obs-backgroundremoval/pull/220 will fix this.

**Closed** 2023-03-31 07:26 UTC
Labels: duplicate
