### ISSUE TITLE
Plugin doesnt Show up

### ISSUE THREAD

**Issue by Stoermy** [royshil/obs-backgroundremoval#72] opened 2022-01-14 21:33 UTC
Hey, first the Folder Background removal is there but it doesnt show up in OBS 64 bit under Cam and Filters.... idk where the Problem ist.

It is installed right.

**Comment by taidos** [comment] 2022-01-17 11:58
Im on the same situation with all the latest versions

**Comment by hunsnowboarder** [comment] 2022-01-19 11:25
Same situation here....

**Comment by tabjy** [comment] 2022-01-19 21:31
Possible duplicate of #37?

**Comment by brotons** [comment] 2022-07-01 09:52
on My OBS version 27.2.4 also not showing up. I think this is still a bug problem.

**Comment by rohaanuv** [comment] 2022-10-06 17:09
obs 28.0.3 can't show the  background removal plugin

**Comment by royshil** [comment] 2023-03-18 21:44
very little information in this issue. i'm closing, and we're tracking this in other issues

**Closed by royshil** 2023-03-18 21:44 UTC
